pipelines:
  branches:
    main:
      - step:
          name: Run Unit Tests
          deployment: Production
          image: ubuntu:20.04
          caches:
            - composer
          script:
            - bash ./bin/pipelines/install_dependencies.sh
            - composer install -o --no-suggest
            - vendor/bin/phpunit
    develop:
      - step:
          name: Deploy to AWS
          deployment: Test
          image: ubuntu:20.04
          caches:
            - composer
          script:
            - bash ./bin/pipelines/install_dependencies.sh
            - composer install -o --no-suggest
            - vendor/bin/phpunit