pipelines:
  branches:
    main:
      - step:
          name: Production Unit Tests
          deployment: Production
          image: composer:2.2.5
          caches:
            - composer
          script:
            - composer install -oqn --no-progress
            - vendor/bin/phpunit --testdox
            - NEXT_VERSION=$(git tag | sort -V | tail -1 | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            - TAG_NAME="${NEXT_VERSION:-1.0.0}"
            - git tag -am "Version ${TAG_NAME} - Build ${BITBUCKET_BUILD_NUMBER}" "${TAG_NAME}" "${BITBUCKET_COMMIT}"
            - git push origin --tags
    develop:
      - step:
          name: Development Unit Tests
          deployment: Test
          image: composer:2.2.5
          caches:
            - composer
          script:
            - composer install -oqn --no-progress
            - vendor/bin/phpunit --testdox
            - NEXT_VERSION=$(git tag | grep -E "\-dev$" | sort -V | tail -1 | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            - TAG_NAME="${NEXT_VERSION:-1.0.0}-dev"
            - git tag -am "Version ${TAG_NAME} - Build ${BITBUCKET_BUILD_NUMBER}" "${TAG_NAME}" "${BITBUCKET_COMMIT}"
            - git push origin --tags