pipelines:
  branches:
    main:
      - step:
          name: Production Unit Tests
          deployment: Production
          image: composer:2.2.5
          caches:
            - composer
          script:
            - composer install -oqn --no-progress
            - vendor/bin/phpunit --testdox
    develop:
      - step:
          name: Development Unit Tests
          deployment: Test
          image: composer:2.2.5
          caches:
            - composer
          script:
            - composer install -oqn --no-progress
            - vendor/bin/phpunit --testdox